### ISSUE TITLE
10/10 Notes

### ISSUE THREAD

**Issue by JogoShugh** [openAgile/CommitStream.Web#3]
# ​​Issue​s / Enhancements:
- ​Most recent events showing up at top of list: will we have to resort to a different Read Model data store or projection or ES query to support ordering an api query by commit date?
# ​​Tech Debt
- Error handling and unit testing of V1 core side.
  - How can we prevent Core builds from being impacted by a remote service call on App Start?
- ​​Unit testing of import functionality and translation
  - Match translator by specific GitHub message version preferentially 
  - Fallback to trying to peel out the required json elements from message 
  - ​​Error handling in node side
- Logging to sumo? Estimably lessons?
- Notifications?
# ​​API response format
- common API formats like HAL and CollectionJson,  etc
- paging information in response 
- parameters for page size
- Docs from embedded code comments
  - What are the best tools for this?
# Installation docs review
- Talk to product specialists
- How much can we automate away entirely? 
  - YAML file for EventStore can be powershell sc produced
- Have more people try them
- Can we describe how to develop under Linux or Mac for people who want to run event store with Mono?
# New ​​Features
- ​Registering a repo event hook via an API call
  ​\* ​In-V1 experience for configuring GitHub repos, similar to Azure experience: starts to get to Digest concept
  ​\* ​Paging / infinite scroll of previous commits in asset detail

**Comment by kunzimariano** [comment]
Some thoughts so far:
- We could start to structure the api a little better, we don't have resources right now we are doing .../api/someAction
- What about using grunt and jshint? Not sure how strict it is.
- Do we need to start thinking about api paging?
- We should split what is inside helpers into proper modules.

**Comment by JogoShugh** [comment]
Good thoughts.  I think we should use jslint for sure. As for grunt, how does it compare with gulp? I don't know much about either. 

Regarding API, I'm still interested in the Swagger approach and plan to read through the articles in this magazine:
http://www.infoq.com/minibooks/emag-API

You bring up a great point about resources too. It's definitely something to be careful with.

**Comment by JogoShugh** [comment]
Here's how to integrate swagger onto Node.js:
https://github.com/wordnik/swagger-node-express

Looks very powerful. I like being able to easily add pipeline interceptions for validations, and I like the declaration of the contract right there in the code which gets turned into live executable documentation.

Here is a project that supports .net WebApi: https://github.com/domaindrivendev/Swashbuckle
